using System;

namespace CameraCli.Native
{
    [Flags]
    public enum DeviceConfigurationFlags : uint //SPDRP_CONFIGFLAGS
    {
        CONFIGFLAG_DISABLED = 0x1,
        CONFIGFLAG_REMOVED = 0x2,
        CONFIGFLAG_MANUAL_INSTALL = 0x4,
        CONFIGFLAG_IGNORE_BOOT_LC = 0x8,
        CONFIGFLAG_NET_BOOT = 0x10,
        CONFIGFLAG_REINSTALL = 0x20,
        CONFIGFLAG_FAILEDINSTALL = 0x40,
        CONFIGFLAG_CANTSTOPACHILD = 0x80,
        CONFIGFLAG_OKREMOVEROM = 0x100,
        CONFIGFLAG_NOREMOVEEXIT = 0x200,
        CONFIGFLAG_FINISH_INSTALL = 0x400,
        CONFIGFLAG_NEEDS_FORCED_CONFIG = 0x800,
        CONFIGFLAG_NETBOOT_CARD = 0x1000,
        CONFIGFLAG_PARTIAL_LOG_CONF = 0x2000,
        CONFIGFLAG_SUPPRESS_SURPRISE = 0x4000,
        CONFIGFLAG_VERIFY_HARDWARE = 0x8000,
        CONFIGFLAG_FINISHINSTALL_UI = 0x10000,
        CONFIGFLAG_FINISHINSTALL_ACTION = 0x20000,
        CONFIGFLAG_BOOT_DEVICE = 0x40000,
        CSCONFIGFLAG_BITS = 0x7,
        CSCONFIGFLAG_DISABLED = 0x1,
        CSCONFIGFLAG_DO_NOT_CREATE = 0x2,
        CSCONFIGFLAG_DO_NOT_START = 0x4
    }
}
