using System;

namespace CameraCli.Native
{
    [Flags]
    internal enum DEVPROPTYPE : uint
    {
        DEVPROP_TYPEMOD_ARRAY = 0x1000,
        DEVPROP_TYPEMOD_LIST = 0x2000,
        DEVPROP_TYPE_EMPTY = 0x0,
        DEVPROP_TYPE_NULL = 0x1,
        DEVPROP_TYPE_SBYTE = 0x2,
        DEVPROP_TYPE_BYTE = 0x3,
        DEVPROP_TYPE_INT16 = 0x4,
        DEVPROP_TYPE_UINT16 = 0x5,
        DEVPROP_TYPE_INT32 = 0x6,
        DEVPROP_TYPE_UINT32 = 0x7,
        DEVPROP_TYPE_INT64 = 0x8,
        DEVPROP_TYPE_UINT64 = 0x9,
        DEVPROP_TYPE_FLOAT = 0xA,
        DEVPROP_TYPE_DOUBLE = 0xB,
        DEVPROP_TYPE_DECIMAL = 0xC,
        DEVPROP_TYPE_GUID = 0xD,
        DEVPROP_TYPE_CURRENCY = 0xE,
        DEVPROP_TYPE_DATE = 0xF,
        DEVPROP_TYPE_FILETIME = 0x10,
        DEVPROP_TYPE_BOOLEAN = 0x11,
        DEVPROP_TYPE_STRING = 0x12,
        DEVPROP_TYPE_SECURITY_DESCRIPTOR = 0x13,
        DEVPROP_TYPE_SECURITY_DESCRIPTOR_STRING = 0x14,
        DEVPROP_TYPE_DEVPROPKEY = 0x15,
        DEVPROP_TYPE_DEVPROPTYPE = 0x16,
        DEVPROP_TYPE_ERROR = 0x17,
        DEVPROP_TYPE_NTSTATUS = 0x18,
        DEVPROP_TYPE_STRING_INDIRECT = 0x19,
        DEVPROP_TYPE_BINARY = 0x1003,
        DEVPROP_TYPE_STRING_LIST = 0x2012
    }
}
